"""change_relashionship_of_categories_and_expensies

Revision ID: ed1acb71ffea
Revises: 
Create Date: 2026-03-03 20:06:23.743134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1acb71ffea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Expense_category_id_fkey'), 'Expense', type_='foreignkey')
    op.drop_column('Expense', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expense', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('Expense_category_id_fkey'), 'Expense', 'Category', ['category_id'], ['id'])
    # ### end Alembic commands ###
